### ISSUE TITLE
Cloud9 being phased out

### ISSUE THREAD

**Issue by dkvaravo** [aws-samples/amazon-neptune-graph-virtualization#1]
As Cloud9 is being [phased out](https://aws.amazon.com/blogs/devops/how-to-migrate-from-aws-cloud9-to-aws-ide-toolkits-or-aws-cloudshell/) I'd like to see an updated CloudFormation stack to address that.

**Comment by mhavey** [comment]
Thank you for raising this. We will test an alternative to Cloud9 and then update the repo accordingly.

**Comment by dkvaravo** [comment]
Thanks for acknowledging. If/when you have an idea whether this will be included in a new release and any timeline would be greatly appreciated. Just to mention, I adjusted the CloudFormation templates to exclude any Cloud9-related services being deployed and the stack succeeded in this way (implicitly I'm saying that the template as it is right now fails to execute completely due to the Cloud9 dependencies)

**Comment by charlesivie** [comment]
@mhavey code review done.

**Comment by mhavey** [comment]
Submitted code change (remove Cloud9 from cfn) and doc change (README). If user does not have a build machine, we give instructions how to use the notebook instance for this purpose.

**Comment by mhavey** [comment]
Closing
